'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('Reviews', [{usersId: "1", gameId: "15", content: "I like game", score: "5"},
      {usersId: "1", gameId: "92", content: "I REALLY like game", score: "2"},
      {usersId: "1", gameId: "192", content: "Game is stupid!", score: "6"},
      {usersId: "1", gameId: "85", content: "HATE this game", score: "1"},
      {usersId: "1", gameId: "183", content: "Please help me, I'm stuck in a test project", score: "8"},
      {usersId: "1", gameId: "192", content: "I am 12 and what is this", score: "9"},
      {usersId: "1", gameId: "116", content: "I have played this game for 50000 hours", score: "6"},
      {usersId: "1", gameId: "130", content: "This game is so indie", score: "2"},
      {usersId: "1", gameId: "54", content: "This game is okay", score: "6"},
      {usersId: "1", gameId: "62", content: "This game is deep and made me think about life", score: "7"},
      {usersId: "1", gameId: "71", content: "Too much MTX", score: "2"},
      {usersId: "1", gameId: "8", content: "Not enough MTX", score: "6"},
      {usersId: "1", gameId: "53", content: "I like game", score: "3"},
      {usersId: "1", gameId: "215", content: "I REALLY like game", score: "8"},
      {usersId: "1", gameId: "95", content: "Game is stupid!", score: "10"},
      {usersId: "1", gameId: "103", content: "HATE this game", score: "1"},
      {usersId: "1", gameId: "235", content: "Please help me, I'm stuck in a test project", score: "10"},
      {usersId: "1", gameId: "138", content: "I am 12 and what is this", score: "4"},
      {usersId: "1", gameId: "30", content: "I have played this game for 50000 hours", score: "5"},
      {usersId: "1", gameId: "39", content: "This game is so indie", score: "3"},
      {usersId: "1", gameId: "53", content: "This game is okay", score: "6"},
      {usersId: "1", gameId: "138", content: "This game is deep and made me think about life", score: "7"},
      {usersId: "1", gameId: "22", content: "Too much MTX", score: "2"},
      {usersId: "1", gameId: "79", content: "Not enough MTX", score: "8"},
      {usersId: "1", gameId: "128", content: "I like game", score: "8"},
      {usersId: "1", gameId: "193", content: "I REALLY like game", score: "10"},
      {usersId: "1", gameId: "195", content: "Game is stupid!", score: "5"},
      {usersId: "1", gameId: "272", content: "HATE this game", score: "4"},
      {usersId: "1", gameId: "223", content: "Please help me, I'm stuck in a test project", score: "1"},
      {usersId: "1", gameId: "202", content: "I am 12 and what is this", score: "9"},
      {usersId: "3", gameId: "165", content: "I have played this game for 50000 hours", score: "5"},
      {usersId: "4", gameId: "81", content: "This game is so indie", score: "9"},
      {usersId: "5", gameId: "131", content: "This game is okay", score: "8"},
      {usersId: "6", gameId: "108", content: "This game is deep and made me think about life", score: "4"},
      {usersId: "7", gameId: "32", content: "Too much MTX", score: "7"},
      {usersId: "8", gameId: "232", content: "Not enough MTX", score: "4"},
      {usersId: "9", gameId: "2", content: "I like game", score: "7"},
      {usersId: "10", gameId: "197", content: "I like game", score: "5"},
      {usersId: "11", gameId: "23", content: "I REALLY like game", score: "7"},
      {usersId: "12", gameId: "90", content: "Game is stupid!", score: "9"},
      {usersId: "13", gameId: "248", content: "HATE this game", score: "5"},
      {usersId: "14", gameId: "213", content: "Please help me, I'm stuck in a test project", score: "2"},
      {usersId: "15", gameId: "96", content: "I am 12 and what is this", score: "7"},
      {usersId: "16", gameId: "71", content: "I have played this game for 50000 hours", score: "4"},
      {usersId: "17", gameId: "219", content: "This game is so indie", score: "7"},
      {usersId: "18", gameId: "89", content: "This game is okay", score: "3"},
      {usersId: "19", gameId: "177", content: "This game is deep and made me think about life", score: "9"},
      {usersId: "20", gameId: "179", content: "Too much MTX", score: "6"},
      {usersId: "21", gameId: "98", content: "Not enough MTX", score: "1"},
      {usersId: "22", gameId: "8", content: "I like game", score: "10"},
      {usersId: "23", gameId: "26", content: "I REALLY like game", score: "10"},
      {usersId: "24", gameId: "158", content: "Game is stupid!", score: "5"},
      {usersId: "25", gameId: "65", content: "HATE this game", score: "10"},
      {usersId: "26", gameId: "39", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "27", gameId: "211", content: "I am 12 and what is this", score: "6"},
      {usersId: "28", gameId: "118", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "1", gameId: "68", content: "This game is so indie", score: "8"},
      {usersId: "2", gameId: "110", content: "This game is okay", score: "5"},
      {usersId: "3", gameId: "40", content: "This game is deep and made me think about life", score: "7"},
      {usersId: "4", gameId: "126", content: "Too much MTX", score: "8"},
      {usersId: "5", gameId: "121", content: "Not enough MTX", score: "6"},
      {usersId: "6", gameId: "267", content: "I like game", score: "8"},
      {usersId: "7", gameId: "109", content: "I REALLY like game", score: "4"},
      {usersId: "8", gameId: "269", content: "Game is stupid!", score: "8"},
      {usersId: "9", gameId: "106", content: "HATE this game", score: "6"},
      {usersId: "10", gameId: "50", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "11", gameId: "242", content: "I am 12 and what is this", score: "5"},
      {usersId: "12", gameId: "235", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "13", gameId: "258", content: "This game is so indie", score: "6"},
      {usersId: "14", gameId: "155", content: "This game is okay", score: "7"},
      {usersId: "15", gameId: "105", content: "This game is deep and made me think about life", score: "9"},
      {usersId: "16", gameId: "231", content: "Too much MTX", score: "10"},
      {usersId: "17", gameId: "148", content: "Not enough MTX", score: "1"},
      {usersId: "18", gameId: "34", content: "I like game", score: "2"},
      {usersId: "19", gameId: "7", content: "I REALLY like game", score: "4"},
      {usersId: "20", gameId: "234", content: "Game is stupid!", score: "9"},
      {usersId: "21", gameId: "134", content: "HATE this game", score: "7"},
      {usersId: "22", gameId: "47", content: "Please help me, I'm stuck in a test project", score: "9"},
      {usersId: "23", gameId: "209", content: "I am 12 and what is this", score: "6"},
      {usersId: "24", gameId: "52", content: "I have played this game for 50000 hours", score: "7"},
      {usersId: "25", gameId: "47", content: "This game is so indie", score: "6"},
      {usersId: "26", gameId: "172", content: "This game is okay", score: "5"},
      {usersId: "27", gameId: "77", content: "This game is deep and made me think about life", score: "10"},
      {usersId: "28", gameId: "184", content: "Too much MTX", score: "4"},
      {usersId: "1", gameId: "105", content: "Not enough MTX", score: "6"},
      {usersId: "2", gameId: "66", content: "I like game", score: "3"},
      {usersId: "3", gameId: "110", content: "I REALLY like game", score: "4"},
      {usersId: "4", gameId: "224", content: "Game is stupid!", score: "1"},
      {usersId: "5", gameId: "16", content: "HATE this game", score: "4"},
      {usersId: "6", gameId: "55", content: "Please help me, I'm stuck in a test project", score: "4"},
      {usersId: "7", gameId: "250", content: "I am 12 and what is this", score: "2"},
      {usersId: "8", gameId: "122", content: "I have played this game for 50000 hours", score: "6"},
      {usersId: "9", gameId: "243", content: "This game is so indie", score: "6"},
      {usersId: "10", gameId: "48", content: "This game is okay", score: "3"},
      {usersId: "11", gameId: "256", content: "This game is deep and made me think about life", score: "5"},
      {usersId: "12", gameId: "26", content: "Too much MTX", score: "8"},
      {usersId: "13", gameId: "235", content: "Not enough MTX", score: "8"},
      {usersId: "14", gameId: "49", content: "I like game", score: "7"},
      {usersId: "15", gameId: "155", content: "I like game", score: "3"},
      {usersId: "16", gameId: "42", content: "I REALLY like game", score: "2"},
      {usersId: "17", gameId: "140", content: "Game is stupid!", score: "2"},
      {usersId: "18", gameId: "35", content: "HATE this game", score: "5"},
      {usersId: "19", gameId: "237", content: "Please help me, I'm stuck in a test project", score: "8"},
      {usersId: "20", gameId: "70", content: "I am 12 and what is this", score: "4"},
      {usersId: "21", gameId: "171", content: "I have played this game for 50000 hours", score: "7"},
      {usersId: "22", gameId: "143", content: "This game is so indie", score: "8"},
      {usersId: "23", gameId: "129", content: "This game is okay", score: "10"},
      {usersId: "24", gameId: "253", content: "This game is deep and made me think about life", score: "4"},
      {usersId: "25", gameId: "35", content: "Too much MTX", score: "9"},
      {usersId: "26", gameId: "13", content: "Not enough MTX", score: "10"},
      {usersId: "27", gameId: "109", content: "I like game", score: "2"},
      {usersId: "28", gameId: "138", content: "I REALLY like game", score: "7"},
      {usersId: "1", gameId: "234", content: "Game is stupid!", score: "5"},
      {usersId: "2", gameId: "231", content: "HATE this game", score: "10"},
      {usersId: "3", gameId: "56", content: "Please help me, I'm stuck in a test project", score: "5"},
      {usersId: "4", gameId: "74", content: "I am 12 and what is this", score: "6"},
      {usersId: "5", gameId: "178", content: "I have played this game for 50000 hours", score: "2"},
      {usersId: "6", gameId: "132", content: "This game is so indie", score: "2"},
      {usersId: "7", gameId: "39", content: "This game is okay", score: "2"},
      {usersId: "8", gameId: "88", content: "This game is deep and made me think about life", score: "3"},
      {usersId: "9", gameId: "2", content: "Too much MTX", score: "9"},
      {usersId: "10", gameId: "181", content: "Not enough MTX", score: "7"},
      {usersId: "11", gameId: "161", content: "I like game", score: "10"},
      {usersId: "12", gameId: "242", content: "I REALLY like game", score: "10"},
      {usersId: "13", gameId: "142", content: "Game is stupid!", score: "2"},
      {usersId: "14", gameId: "106", content: "HATE this game", score: "10"},
      {usersId: "15", gameId: "208", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "16", gameId: "193", content: "I am 12 and what is this", score: "4"},
      {usersId: "17", gameId: "195", content: "I have played this game for 50000 hours", score: "1"},
      {usersId: "18", gameId: "268", content: "This game is so indie", score: "2"},
      {usersId: "19", gameId: "162", content: "This game is okay", score: "8"},
      {usersId: "20", gameId: "256", content: "This game is deep and made me think about life", score: "1"},
      {usersId: "21", gameId: "249", content: "Too much MTX", score: "6"},
      {usersId: "22", gameId: "72", content: "Not enough MTX", score: "7"},
      {usersId: "23", gameId: "176", content: "I like game", score: "2"},
      {usersId: "24", gameId: "247", content: "I REALLY like game", score: "9"},
      {usersId: "25", gameId: "235", content: "Game is stupid!", score: "1"},
      {usersId: "26", gameId: "172", content: "HATE this game", score: "2"},
      {usersId: "27", gameId: "227", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "28", gameId: "140", content: "I am 12 and what is this", score: "1"},
      {usersId: "1", gameId: "180", content: "I have played this game for 50000 hours", score: "7"},
      {usersId: "2", gameId: "255", content: "This game is so indie", score: "2"},
      {usersId: "3", gameId: "174", content: "This game is okay", score: "2"},
      {usersId: "4", gameId: "5", content: "This game is deep and made me think about life", score: "8"},
      {usersId: "5", gameId: "180", content: "Too much MTX", score: "6"},
      {usersId: "6", gameId: "266", content: "Not enough MTX", score: "4"},
      {usersId: "7", gameId: "247", content: "I like game", score: "10"},
      {usersId: "8", gameId: "75", content: "I REALLY like game", score: "2"},
      {usersId: "9", gameId: "47", content: "Game is stupid!", score: "1"},
      {usersId: "10", gameId: "137", content: "HATE this game", score: "10"},
      {usersId: "11", gameId: "87", content: "Please help me, I'm stuck in a test project", score: "2"},
      {usersId: "12", gameId: "48", content: "I am 12 and what is this", score: "8"},
      {usersId: "13", gameId: "95", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "14", gameId: "70", content: "This game is so indie", score: "1"},
      {usersId: "15", gameId: "185", content: "This game is okay", score: "8"},
      {usersId: "16", gameId: "60", content: "This game is deep and made me think about life", score: "1"},
      {usersId: "17", gameId: "239", content: "Too much MTX", score: "4"},
      {usersId: "18", gameId: "86", content: "Not enough MTX", score: "8"},
      {usersId: "19", gameId: "71", content: "I like game", score: "9"},
      {usersId: "20", gameId: "124", content: "I like game", score: "9"},
      {usersId: "21", gameId: "265", content: "I REALLY like game", score: "1"},
      {usersId: "22", gameId: "249", content: "Game is stupid!", score: "5"},
      {usersId: "23", gameId: "237", content: "HATE this game", score: "7"},
      {usersId: "24", gameId: "48", content: "Please help me, I'm stuck in a test project", score: "2"},
      {usersId: "25", gameId: "127", content: "I am 12 and what is this", score: "5"},
      {usersId: "26", gameId: "175", content: "I have played this game for 50000 hours", score: "4"},
      {usersId: "27", gameId: "268", content: "This game is so indie", score: "2"},
      {usersId: "28", gameId: "92", content: "This game is okay", score: "5"},
      {usersId: "1", gameId: "62", content: "This game is deep and made me think about life", score: "5"},
      {usersId: "2", gameId: "256", content: "Too much MTX", score: "4"},
      {usersId: "3", gameId: "127", content: "Not enough MTX", score: "9"},
      {usersId: "4", gameId: "31", content: "I like game", score: "5"},
      {usersId: "5", gameId: "244", content: "I REALLY like game", score: "8"},
      {usersId: "6", gameId: "174", content: "Game is stupid!", score: "2"},
      {usersId: "7", gameId: "244", content: "HATE this game", score: "2"},
      {usersId: "8", gameId: "180", content: "Please help me, I'm stuck in a test project", score: "2"},
      {usersId: "9", gameId: "130", content: "I am 12 and what is this", score: "10"},
      {usersId: "10", gameId: "120", content: "I have played this game for 50000 hours", score: "7"},
      {usersId: "11", gameId: "118", content: "This game is so indie", score: "7"},
      {usersId: "12", gameId: "22", content: "This game is okay", score: "4"},
      {usersId: "13", gameId: "85", content: "This game is deep and made me think about life", score: "1"},
      {usersId: "14", gameId: "95", content: "Too much MTX", score: "4"},
      {usersId: "15", gameId: "56", content: "Not enough MTX", score: "10"},
      {usersId: "16", gameId: "51", content: "Not enough MTX", score: "1"},
      {usersId: "17", gameId: "200", content: "I like game", score: "1"},
      {usersId: "18", gameId: "160", content: "I REALLY like game", score: "10"},
      {usersId: "19", gameId: "241", content: "Game is stupid!", score: "2"},
      {usersId: "20", gameId: "159", content: "HATE this game", score: "5"},
      {usersId: "21", gameId: "253", content: "Please help me, I'm stuck in a test project", score: "10"},
      {usersId: "22", gameId: "98", content: "I am 12 and what is this", score: "9"},
      {usersId: "23", gameId: "235", content: "I have played this game for 50000 hours", score: "3"},
      {usersId: "24", gameId: "90", content: "This game is so indie", score: "3"},
      {usersId: "25", gameId: "53", content: "This game is okay", score: "2"},
      {usersId: "26", gameId: "189", content: "This game is deep and made me think about life", score: "10"},
      {usersId: "27", gameId: "147", content: "Too much MTX", score: "4"},
      {usersId: "28", gameId: "240", content: "Not enough MTX", score: "3"},
      {usersId: "1", gameId: "186", content: "I like game", score: "10"},
      {usersId: "2", gameId: "60", content: "I REALLY like game", score: "5"},
      {usersId: "3", gameId: "118", content: "Game is stupid!", score: "4"},
      {usersId: "4", gameId: "66", content: "HATE this game", score: "4"},
      {usersId: "5", gameId: "144", content: "Please help me, I'm stuck in a test project", score: "3"},
      {usersId: "6", gameId: "237", content: "I am 12 and what is this", score: "7"},
      {usersId: "7", gameId: "155", content: "I have played this game for 50000 hours", score: "7"},
      {usersId: "8", gameId: "239", content: "This game is so indie", score: "2"},
      {usersId: "9", gameId: "260", content: "This game is okay", score: "6"},
      {usersId: "10", gameId: "217", content: "This game is deep and made me think about life", score: "7"},
      {usersId: "11", gameId: "17", content: "Too much MTX", score: "7"},
      {usersId: "12", gameId: "236", content: "Not enough MTX", score: "4"},
      {usersId: "13", gameId: "226", content: "I like game", score: "7"},
      {usersId: "14", gameId: "141", content: "I REALLY like game", score: "3"},
      {usersId: "15", gameId: "268", content: "Game is stupid!", score: "10"},
      {usersId: "16", gameId: "130", content: "HATE this game", score: "5"},
      {usersId: "17", gameId: "185", content: "Please help me, I'm stuck in a test project", score: "4"},
      {usersId: "18", gameId: "260", content: "I am 12 and what is this", score: "8"},
      {usersId: "19", gameId: "143", content: "I have played this game for 50000 hours", score: "10"},
      {usersId: "20", gameId: "54", content: "This game is so indie", score: "2"},
      {usersId: "21", gameId: "70", content: "This game is okay", score: "9"},
      {usersId: "22", gameId: "23", content: "This game is deep and made me think about life", score: "8"},
      {usersId: "23", gameId: "228", content: "Too much MTX", score: "2"},
      {usersId: "24", gameId: "221", content: "Not enough MTX", score: "9"},
      {usersId: "25", gameId: "233", content: "I like game", score: "9"},
      {usersId: "26", gameId: "159", content: "I like game", score: "5"},
      {usersId: "27", gameId: "58", content: "I REALLY like game", score: "8"},
      {usersId: "28", gameId: "241", content: "Game is stupid!", score: "1"},
      {usersId: "1", gameId: "194", content: "HATE this game", score: "4"},
      {usersId: "2", gameId: "251", content: "Please help me, I'm stuck in a test project", score: "2"},
      {usersId: "3", gameId: "233", content: "I am 12 and what is this", score: "3"},
      {usersId: "4", gameId: "226", content: "I have played this game for 50000 hours", score: "6"},
      {usersId: "5", gameId: "105", content: "This game is so indie", score: "9"},
      {usersId: "6", gameId: "26", content: "This game is okay", score: "1"},
      {usersId: "7", gameId: "93", content: "This game is deep and made me think about life", score: "3"},
      {usersId: "8", gameId: "228", content: "Too much MTX", score: "3"},
      {usersId: "9", gameId: "47", content: "Not enough MTX", score: "3"},
      {usersId: "10", gameId: "235", content: "I like game", score: "7"},
      {usersId: "11", gameId: "244", content: "I REALLY like game", score: "4"},
      {usersId: "12", gameId: "183", content: "Game is stupid!", score: "1"},
      {usersId: "13", gameId: "191", content: "HATE this game", score: "6"},
      {usersId: "14", gameId: "105", content: "Please help me, I'm stuck in a test project", score: "2"},
      {usersId: "15", gameId: "181", content: "I am 12 and what is this", score: "7"},
      {usersId: "16", gameId: "117", content: "I have played this game for 50000 hours", score: "4"},
      {usersId: "17", gameId: "272", content: "This game is so indie", score: "2"},
      {usersId: "18", gameId: "203", content: "This game is okay", score: "5"},
      {usersId: "19", gameId: "146", content: "This game is deep and made me think about life", score: "10"},
      {usersId: "20", gameId: "224", content: "Too much MTX", score: "8"},
      {usersId: "21", gameId: "48", content: "Not enough MTX", score: "9"},
      {usersId: "22", gameId: "21", content: "I like game", score: "8"},
      {usersId: "23", gameId: "48", content: "I REALLY like game", score: "9"},
      {usersId: "24", gameId: "58", content: "Game is stupid!", score: "1"},
      {usersId: "25", gameId: "267", content: "HATE this game", score: "7"},
      {usersId: "26", gameId: "207", content: "Please help me, I'm stuck in a test project", score: "2"},
      {usersId: "27", gameId: "107", content: "I am 12 and what is this", score: "10"},
      {usersId: "28", gameId: "223", content: "I have played this game for 50000 hours", score: "2"},
      {usersId: "1", gameId: "166", content: "This game is so indie", score: "2"},
      {usersId: "2", gameId: "35", content: "This game is okay", score: "5"},
      {usersId: "3", gameId: "190", content: "This game is deep and made me think about life", score: "4"},
      {usersId: "4", gameId: "19", content: "Too much MTX", score: "3"},
      {usersId: "5", gameId: "87", content: "Not enough MTX", score: "6"},
      {usersId: "6", gameId: "89", content: "I like game", score: "1"},
      {usersId: "7", gameId: "274", content: "I REALLY like game", score: "5"},
      {usersId: "8", gameId: "267", content: "Game is stupid!", score: "5"},
      {usersId: "9", gameId: "135", content: "HATE this game", score: "8"},
      {usersId: "10", gameId: "244", content: "Please help me, I'm stuck in a test project", score: "5"},
      {usersId: "11", gameId: "74", content: "I am 12 and what is this", score: "4"},
      {usersId: "12", gameId: "203", content: "I have played this game for 50000 hours", score: "7"},
      {usersId: "13", gameId: "95", content: "This game is so indie", score: "7"},
      {usersId: "14", gameId: "69", content: "This game is okay", score: "4"},
      {usersId: "15", gameId: "194", content: "This game is deep and made me think about life", score: "6"},
      {usersId: "16", gameId: "201", content: "Too much MTX", score: "6"},
      {usersId: "17", gameId: "93", content: "Not enough MTX", score: "9"},
      {usersId: "18", gameId: "138", content: "I like game", score: "2"},
      {usersId: "19", gameId: "105", content: "I REALLY like game", score: "2"},
      {usersId: "20", gameId: "43", content: "Game is stupid!", score: "9"},
      {usersId: "21", gameId: "122", content: "HATE this game", score: "1"},
      {usersId: "22", gameId: "127", content: "Please help me, I'm stuck in a test project", score: "3"},
      {usersId: "23", gameId: "199", content: "I am 12 and what is this", score: "7"},
      {usersId: "24", gameId: "261", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "25", gameId: "232", content: "This game is so indie", score: "8"},
      {usersId: "26", gameId: "235", content: "This game is okay", score: "8"},
      {usersId: "27", gameId: "276", content: "This game is deep and made me think about life", score: "6"},
      {usersId: "28", gameId: "237", content: "Too much MTX", score: "8"},
      {usersId: "1", gameId: "248", content: "Not enough MTX", score: "6"},
      {usersId: "2", gameId: "265", content: "I like game", score: "7"},
      {usersId: "3", gameId: "220", content: "I like game", score: "7"},
      {usersId: "4", gameId: "97", content: "I REALLY like game", score: "6"},
      {usersId: "5", gameId: "101", content: "Game is stupid!", score: "9"},
      {usersId: "6", gameId: "58", content: "HATE this game", score: "9"},
      {usersId: "7", gameId: "237", content: "Please help me, I'm stuck in a test project", score: "9"},
      {usersId: "8", gameId: "140", content: "I am 12 and what is this", score: "2"},
      {usersId: "9", gameId: "6", content: "I have played this game for 50000 hours", score: "3"},
      {usersId: "10", gameId: "220", content: "This game is so indie", score: "3"},
      {usersId: "11", gameId: "174", content: "This game is okay", score: "1"},
      {usersId: "12", gameId: "21", content: "This game is deep and made me think about life", score: "4"},
      {usersId: "13", gameId: "3", content: "Too much MTX", score: "1"},
      {usersId: "14", gameId: "181", content: "Not enough MTX", score: "2"},
      {usersId: "15", gameId: "115", content: "I like game", score: "3"},
      {usersId: "16", gameId: "120", content: "I REALLY like game", score: "8"},
      {usersId: "17", gameId: "228", content: "Game is stupid!", score: "3"},
      {usersId: "18", gameId: "207", content: "HATE this game", score: "2"},
      {usersId: "19", gameId: "263", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "20", gameId: "210", content: "I am 12 and what is this", score: "2"},
      {usersId: "21", gameId: "253", content: "I have played this game for 50000 hours", score: "3"},
      {usersId: "22", gameId: "119", content: "This game is so indie", score: "7"},
      {usersId: "23", gameId: "143", content: "This game is okay", score: "2"},
      {usersId: "24", gameId: "185", content: "This game is deep and made me think about life", score: "7"},
      {usersId: "25", gameId: "256", content: "Too much MTX", score: "1"},
      {usersId: "26", gameId: "252", content: "Not enough MTX", score: "7"},
      {usersId: "27", gameId: "216", content: "I like game", score: "6"},
      {usersId: "28", gameId: "61", content: "I REALLY like game", score: "6"},
      {usersId: "1", gameId: "231", content: "Game is stupid!", score: "9"},
      {usersId: "2", gameId: "214", content: "HATE this game", score: "4"},
      {usersId: "3", gameId: "99", content: "Please help me, I'm stuck in a test project", score: "7"},
      {usersId: "4", gameId: "203", content: "I am 12 and what is this", score: "2"},
      {usersId: "5", gameId: "202", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "6", gameId: "154", content: "This game is so indie", score: "7"},
      {usersId: "7", gameId: "237", content: "This game is okay", score: "2"},
      {usersId: "8", gameId: "66", content: "This game is deep and made me think about life", score: "5"},
      {usersId: "9", gameId: "140", content: "Too much MTX", score: "5"},
      {usersId: "10", gameId: "139", content: "Not enough MTX", score: "2"},
      {usersId: "11", gameId: "148", content: "I like game", score: "9"},
      {usersId: "12", gameId: "272", content: "I REALLY like game", score: "3"},
      {usersId: "13", gameId: "79", content: "Game is stupid!", score: "10"},
      {usersId: "14", gameId: "258", content: "HATE this game", score: "10"},
      {usersId: "15", gameId: "19", content: "Please help me, I'm stuck in a test project", score: "8"},
      {usersId: "16", gameId: "230", content: "I am 12 and what is this", score: "7"},
      {usersId: "17", gameId: "265", content: "I have played this game for 50000 hours", score: "8"},
      {usersId: "18", gameId: "45", content: "This game is so indie", score: "10"},
      {usersId: "19", gameId: "76", content: "This game is okay", score: "1"},
      {usersId: "20", gameId: "34", content: "This game is deep and made me think about life", score: "7"},
      {usersId: "21", gameId: "41", content: "Too much MTX", score: "8"},
      {usersId: "22", gameId: "245", content: "Not enough MTX", score: "1"},
      {usersId: "23", gameId: "80", content: "I like game", score: "5"},
      {usersId: "24", gameId: "32", content: "I REALLY like game", score: "5"},
      {usersId: "25", gameId: "102", content: "Game is stupid!", score: "3"},
      {usersId: "26", gameId: "29", content: "HATE this game", score: "10"},
      {usersId: "27", gameId: "159", content: "Please help me, I'm stuck in a test project", score: "7"},
      {usersId: "28", gameId: "275", content: "I am 12 and what is this", score: "8"},
      {usersId: "1", gameId: "38", content: "I have played this game for 50000 hours", score: "1"},
      {usersId: "2", gameId: "62", content: "This game is so indie", score: "9"},
      {usersId: "3", gameId: "16", content: "This game is okay", score: "10"},
      {usersId: "4", gameId: "125", content: "This game is deep and made me think about life", score: "10"},
      {usersId: "5", gameId: "253", content: "Too much MTX", score: "3"},
      {usersId: "6", gameId: "118", content: "Not enough MTX", score: "10"},
      {usersId: "7", gameId: "137", content: "I like game", score: "9"},
      {usersId: "8", gameId: "70", content: "I like game", score: "9"},
      {usersId: "9", gameId: "25", content: "I REALLY like game", score: "4"},
      {usersId: "10", gameId: "141", content: "Game is stupid!", score: "5"},
      {usersId: "11", gameId: "59", content: "HATE this game", score: "8"},
      {usersId: "12", gameId: "188", content: "Please help me, I'm stuck in a test project", score: "4"},
      {usersId: "13", gameId: "149", content: "I am 12 and what is this", score: "5"},
      {usersId: "14", gameId: "35", content: "I have played this game for 50000 hours", score: "5"},
      {usersId: "15", gameId: "2", content: "This game is so indie", score: "9"},
      {usersId: "16", gameId: "192", content: "This game is okay", score: "3"},
      {usersId: "17", gameId: "260", content: "This game is deep and made me think about life", score: "4"},
      {usersId: "18", gameId: "149", content: "Too much MTX", score: "9"},
      {usersId: "19", gameId: "62", content: "Not enough MTX", score: "4"},
      {usersId: "20", gameId: "24", content: "I like game", score: "5"},
      {usersId: "21", gameId: "98", content: "I REALLY like game", score: "10"},
      {usersId: "22", gameId: "200", content: "Game is stupid!", score: "8"},
      {usersId: "23", gameId: "95", content: "HATE this game", score: "9"},
      {usersId: "24", gameId: "208", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "25", gameId: "66", content: "I am 12 and what is this", score: "9"},
      {usersId: "26", gameId: "242", content: "I have played this game for 50000 hours", score: "8"},
      {usersId: "27", gameId: "209", content: "This game is so indie", score: "8"},
      {usersId: "28", gameId: "31", content: "This game is okay", score: "1"},
      {usersId: "1", gameId: "109", content: "This game is deep and made me think about life", score: "6"},
      {usersId: "2", gameId: "80", content: "Too much MTX", score: "10"},
      {usersId: "3", gameId: "225", content: "Not enough MTX", score: "8"},
      {usersId: "4", gameId: "192", content: "I like game", score: "5"},
      {usersId: "5", gameId: "39", content: "I REALLY like game", score: "10"},
      {usersId: "6", gameId: "147", content: "Game is stupid!", score: "10"},
      {usersId: "7", gameId: "36", content: "HATE this game", score: "5"},
      {usersId: "8", gameId: "205", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "9", gameId: "127", content: "I am 12 and what is this", score: "7"},
      {usersId: "10", gameId: "46", content: "I have played this game for 50000 hours", score: "8"},
      {usersId: "11", gameId: "12", content: "This game is so indie", score: "7"},
      {usersId: "12", gameId: "191", content: "This game is okay", score: "6"},
      {usersId: "13", gameId: "71", content: "This game is deep and made me think about life", score: "9"},
      {usersId: "14", gameId: "213", content: "Too much MTX", score: "6"},
      {usersId: "15", gameId: "137", content: "Not enough MTX", score: "9"},
      {usersId: "16", gameId: "42", content: "I like game", score: "1"},
      {usersId: "17", gameId: "121", content: "I REALLY like game", score: "3"},
      {usersId: "18", gameId: "102", content: "Game is stupid!", score: "10"},
      {usersId: "19", gameId: "197", content: "HATE this game", score: "5"},
      {usersId: "20", gameId: "62", content: "Please help me, I'm stuck in a test project", score: "7"},
      {usersId: "21", gameId: "218", content: "I am 12 and what is this", score: "5"},
      {usersId: "22", gameId: "251", content: "I have played this game for 50000 hours", score: "5"},
      {usersId: "23", gameId: "58", content: "This game is so indie", score: "2"},
      {usersId: "24", gameId: "228", content: "This game is okay", score: "5"},
      {usersId: "25", gameId: "134", content: "This game is deep and made me think about life", score: "2"},
      {usersId: "26", gameId: "38", content: "Too much MTX", score: "1"},
      {usersId: "27", gameId: "226", content: "Not enough MTX", score: "8"},
      {usersId: "28", gameId: "83", content: "I like game", score: "5"},
      {usersId: "1", gameId: "266", content: "I REALLY like game", score: "1"},
      {usersId: "2", gameId: "169", content: "Game is stupid!", score: "5"},
      {usersId: "3", gameId: "73", content: "HATE this game", score: "9"},
      {usersId: "4", gameId: "242", content: "Please help me, I'm stuck in a test project", score: "5"},
      {usersId: "5", gameId: "148", content: "I am 12 and what is this", score: "2"},
      {usersId: "6", gameId: "136", content: "I have played this game for 50000 hours", score: "4"},
      {usersId: "7", gameId: "11", content: "This game is so indie", score: "9"},
      {usersId: "8", gameId: "233", content: "This game is okay", score: "10"},
      {usersId: "9", gameId: "128", content: "This game is deep and made me think about life", score: "10"},
      {usersId: "10", gameId: "67", content: "Too much MTX", score: "6"},
      {usersId: "11", gameId: "85", content: "Not enough MTX", score: "9"},
      {usersId: "12", gameId: "101", content: "I like game", score: "4"},
      {usersId: "13", gameId: "60", content: "I like game", score: "6"},
      {usersId: "14", gameId: "121", content: "I REALLY like game", score: "9"},
      {usersId: "15", gameId: "178", content: "Game is stupid!", score: "9"},
      {usersId: "16", gameId: "87", content: "HATE this game", score: "2"},
      {usersId: "17", gameId: "104", content: "Please help me, I'm stuck in a test project", score: "5"},
      {usersId: "18", gameId: "101", content: "I am 12 and what is this", score: "8"},
      {usersId: "19", gameId: "244", content: "I have played this game for 50000 hours", score: "3"},
      {usersId: "20", gameId: "256", content: "This game is so indie", score: "3"},
      {usersId: "21", gameId: "173", content: "This game is okay", score: "6"},
      {usersId: "22", gameId: "41", content: "This game is deep and made me think about life", score: "5"},
      {usersId: "23", gameId: "260", content: "Too much MTX", score: "7"},
      {usersId: "24", gameId: "54", content: "Not enough MTX", score: "8"},
      {usersId: "25", gameId: "180", content: "I like game", score: "5"},
      {usersId: "26", gameId: "25", content: "I REALLY like game", score: "1"},
      {usersId: "27", gameId: "271", content: "Game is stupid!", score: "5"},
      {usersId: "28", gameId: "14", content: "HATE this game", score: "6"},
      {usersId: "1", gameId: "193", content: "Please help me, I'm stuck in a test project", score: "2"},
      {usersId: "2", gameId: "45", content: "I am 12 and what is this", score: "10"},
      {usersId: "3", gameId: "116", content: "I have played this game for 50000 hours", score: "5"},
      {usersId: "4", gameId: "141", content: "This game is so indie", score: "5"},
      {usersId: "5", gameId: "237", content: "This game is okay", score: "10"},
      {usersId: "6", gameId: "198", content: "This game is deep and made me think about life", score: "1"},
      {usersId: "7", gameId: "247", content: "Too much MTX", score: "2"},
      {usersId: "8", gameId: "44", content: "Not enough MTX", score: "5"},
      {usersId: "9", gameId: "91", content: "Not enough MTX", score: "10"},
      {usersId: "10", gameId: "217", content: "I like game", score: "5"},
      {usersId: "11", gameId: "123", content: "I REALLY like game", score: "3"},
      {usersId: "12", gameId: "266", content: "Game is stupid!", score: "10"},
      {usersId: "13", gameId: "259", content: "HATE this game", score: "3"},
      {usersId: "14", gameId: "255", content: "Please help me, I'm stuck in a test project", score: "4"},
      {usersId: "15", gameId: "226", content: "I am 12 and what is this", score: "7"},
      {usersId: "16", gameId: "99", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "17", gameId: "67", content: "This game is so indie", score: "3"},
      {usersId: "18", gameId: "83", content: "This game is okay", score: "10"},
      {usersId: "19", gameId: "16", content: "This game is deep and made me think about life", score: "1"},
      {usersId: "20", gameId: "80", content: "Too much MTX", score: "9"},
      {usersId: "21", gameId: "87", content: "Not enough MTX", score: "2"},
      {usersId: "22", gameId: "220", content: "I like game", score: "8"},
      {usersId: "23", gameId: "144", content: "I REALLY like game", score: "9"},
      {usersId: "24", gameId: "263", content: "Game is stupid!", score: "8"},
      {usersId: "25", gameId: "159", content: "HATE this game", score: "10"},
      {usersId: "26", gameId: "24", content: "Please help me, I'm stuck in a test project", score: "3"},
      {usersId: "27", gameId: "270", content: "I am 12 and what is this", score: "9"},
      {usersId: "28", gameId: "59", content: "I have played this game for 50000 hours", score: "2"},
      {usersId: "1", gameId: "185", content: "This game is so indie", score: "10"},
      {usersId: "2", gameId: "244", content: "This game is okay", score: "8"},
      {usersId: "3", gameId: "195", content: "This game is deep and made me think about life", score: "9"},
      {usersId: "4", gameId: "53", content: "Too much MTX", score: "1"},
      {usersId: "5", gameId: "96", content: "Not enough MTX", score: "10"},
      {usersId: "6", gameId: "17", content: "I like game", score: "2"},
      {usersId: "7", gameId: "93", content: "I REALLY like game", score: "8"},
      {usersId: "8", gameId: "18", content: "Game is stupid!", score: "10"},
      {usersId: "9", gameId: "245", content: "HATE this game", score: "2"},
      {usersId: "10", gameId: "245", content: "Please help me, I'm stuck in a test project", score: "3"},
      {usersId: "11", gameId: "206", content: "I am 12 and what is this", score: "2"},
      {usersId: "12", gameId: "233", content: "I have played this game for 50000 hours", score: "3"},
      {usersId: "13", gameId: "153", content: "This game is so indie", score: "6"},
      {usersId: "14", gameId: "189", content: "This game is okay", score: "3"},
      {usersId: "15", gameId: "146", content: "This game is deep and made me think about life", score: "1"},
      {usersId: "16", gameId: "252", content: "Too much MTX", score: "3"},
      {usersId: "17", gameId: "235", content: "Not enough MTX", score: "1"},
      {usersId: "18", gameId: "118", content: "I like game", score: "8"},
      {usersId: "19", gameId: "259", content: "I like game", score: "8"},
      {usersId: "20", gameId: "221", content: "I REALLY like game", score: "3"},
      {usersId: "21", gameId: "221", content: "Game is stupid!", score: "7"},
      {usersId: "22", gameId: "182", content: "HATE this game", score: "7"},
      {usersId: "23", gameId: "141", content: "Please help me, I'm stuck in a test project", score: "7"},
      {usersId: "24", gameId: "142", content: "I am 12 and what is this", score: "8"},
      {usersId: "25", gameId: "181", content: "I have played this game for 50000 hours", score: "10"},
      {usersId: "26", gameId: "156", content: "This game is so indie", score: "6"},
      {usersId: "27", gameId: "110", content: "This game is okay", score: "9"},
      {usersId: "28", gameId: "46", content: "This game is deep and made me think about life", score: "9"},
      {usersId: "1", gameId: "250", content: "Too much MTX", score: "9"},
      {usersId: "2", gameId: "114", content: "Not enough MTX", score: "4"},
      {usersId: "3", gameId: "196", content: "I like game", score: "2"},
      {usersId: "4", gameId: "75", content: "I REALLY like game", score: "10"},
      {usersId: "5", gameId: "208", content: "Game is stupid!", score: "8"},
      {usersId: "6", gameId: "156", content: "HATE this game", score: "8"},
      {usersId: "7", gameId: "126", content: "Please help me, I'm stuck in a test project", score: "10"},
      {usersId: "8", gameId: "178", content: "I am 12 and what is this", score: "7"},
      {usersId: "9", gameId: "243", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "10", gameId: "70", content: "This game is so indie", score: "7"},
      {usersId: "11", gameId: "151", content: "This game is okay", score: "2"},
      {usersId: "12", gameId: "247", content: "This game is deep and made me think about life", score: "4"},
      {usersId: "13", gameId: "231", content: "Too much MTX", score: "10"},
      {usersId: "14", gameId: "83", content: "Not enough MTX", score: "8"},
      {usersId: "15", gameId: "191", content: "I like game", score: "10"},
      {usersId: "16", gameId: "154", content: "I REALLY like game", score: "7"},
      {usersId: "17", gameId: "265", content: "Game is stupid!", score: "10"},
      {usersId: "18", gameId: "261", content: "HATE this game", score: "1"},
      {usersId: "19", gameId: "130", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "20", gameId: "268", content: "I am 12 and what is this", score: "1"},
      {usersId: "21", gameId: "151", content: "I have played this game for 50000 hours", score: "5"},
      {usersId: "22", gameId: "40", content: "This game is so indie", score: "1"},
      {usersId: "23", gameId: "5", content: "This game is okay", score: "9"},
      {usersId: "24", gameId: "50", content: "This game is deep and made me think about life", score: "8"},
      {usersId: "25", gameId: "93", content: "Too much MTX", score: "2"},
      {usersId: "26", gameId: "73", content: "Not enough MTX", score: "10"},
      {usersId: "27", gameId: "157", content: "I like game", score: "4"},
      {usersId: "28", gameId: "62", content: "I REALLY like game", score: "2"},
      {usersId: "1", gameId: "246", content: "Game is stupid!", score: "7"},
      {usersId: "2", gameId: "265", content: "HATE this game", score: "9"},
      {usersId: "3", gameId: "51", content: "Please help me, I'm stuck in a test project", score: "10"},
      {usersId: "4", gameId: "175", content: "I am 12 and what is this", score: "5"},
      {usersId: "5", gameId: "21", content: "I have played this game for 50000 hours", score: "10"},
      {usersId: "6", gameId: "41", content: "This game is so indie", score: "3"},
      {usersId: "7", gameId: "249", content: "This game is okay", score: "4"},
      {usersId: "8", gameId: "114", content: "This game is deep and made me think about life", score: "3"},
      {usersId: "9", gameId: "181", content: "Too much MTX", score: "8"},
      {usersId: "10", gameId: "244", content: "Not enough MTX", score: "2"},
      {usersId: "11", gameId: "56", content: "I like game", score: "4"},
      {usersId: "12", gameId: "54", content: "I REALLY like game", score: "1"},
      {usersId: "13", gameId: "224", content: "Game is stupid!", score: "2"},
      {usersId: "14", gameId: "238", content: "HATE this game", score: "6"},
      {usersId: "15", gameId: "48", content: "Please help me, I'm stuck in a test project", score: "7"},
      {usersId: "16", gameId: "273", content: "I am 12 and what is this", score: "7"},
      {usersId: "17", gameId: "213", content: "I have played this game for 50000 hours", score: "3"},
      {usersId: "18", gameId: "88", content: "This game is so indie", score: "4"},
      {usersId: "19", gameId: "110", content: "This game is okay", score: "1"},
      {usersId: "20", gameId: "161", content: "This game is deep and made me think about life", score: "4"},
      {usersId: "21", gameId: "81", content: "Too much MTX", score: "9"},
      {usersId: "22", gameId: "16", content: "Not enough MTX", score: "7"},
      {usersId: "23", gameId: "32", content: "I like game", score: "1"},
      {usersId: "24", gameId: "5", content: "I like game", score: "9"},
      {usersId: "25", gameId: "165", content: "I REALLY like game", score: "10"},
      {usersId: "26", gameId: "132", content: "Game is stupid!", score: "10"},
      {usersId: "27", gameId: "10", content: "HATE this game", score: "2"},
      {usersId: "28", gameId: "112", content: "Please help me, I'm stuck in a test project", score: "10"},
      {usersId: "1", gameId: "53", content: "I am 12 and what is this", score: "5"},
      {usersId: "2", gameId: "79", content: "I have played this game for 50000 hours", score: "8"},
      {usersId: "3", gameId: "237", content: "This game is so indie", score: "5"},
      {usersId: "4", gameId: "11", content: "This game is okay", score: "5"},
      {usersId: "5", gameId: "66", content: "This game is deep and made me think about life", score: "7"},
      {usersId: "6", gameId: "264", content: "Too much MTX", score: "9"},
      {usersId: "7", gameId: "113", content: "Not enough MTX", score: "5"},
      {usersId: "8", gameId: "89", content: "I like game", score: "4"},
      {usersId: "9", gameId: "68", content: "I REALLY like game", score: "4"},
      {usersId: "10", gameId: "77", content: "Game is stupid!", score: "4"},
      {usersId: "11", gameId: "265", content: "HATE this game", score: "3"},
      {usersId: "12", gameId: "260", content: "Please help me, I'm stuck in a test project", score: "7"},
      {usersId: "13", gameId: "183", content: "I am 12 and what is this", score: "4"},
      {usersId: "14", gameId: "223", content: "I have played this game for 50000 hours", score: "3"},
      {usersId: "15", gameId: "177", content: "This game is so indie", score: "4"},
      {usersId: "16", gameId: "36", content: "This game is okay", score: "2"},
      {usersId: "17", gameId: "240", content: "This game is deep and made me think about life", score: "8"},
      {usersId: "18", gameId: "102", content: "Too much MTX", score: "2"},
      {usersId: "19", gameId: "218", content: "Not enough MTX", score: "8"},
      {usersId: "20", gameId: "111", content: "I like game", score: "2"},
      {usersId: "21", gameId: "145", content: "I REALLY like game", score: "10"},
      {usersId: "22", gameId: "18", content: "Game is stupid!", score: "3"},
      {usersId: "23", gameId: "217", content: "HATE this game", score: "6"},
      {usersId: "24", gameId: "166", content: "Please help me, I'm stuck in a test project", score: "10"},
      {usersId: "25", gameId: "196", content: "I am 12 and what is this", score: "2"},
      {usersId: "26", gameId: "169", content: "I have played this game for 50000 hours", score: "10"},
      {usersId: "27", gameId: "175", content: "This game is so indie", score: "4"},
      {usersId: "28", gameId: "46", content: "This game is okay", score: "9"},
      {usersId: "1", gameId: "69", content: "This game is deep and made me think about life", score: "5"},
      {usersId: "2", gameId: "32", content: "Too much MTX", score: "10"},
      {usersId: "3", gameId: "89", content: "Not enough MTX", score: "10"},
      {usersId: "4", gameId: "220", content: "I like game", score: "4"},
      {usersId: "5", gameId: "253", content: "I REALLY like game", score: "5"},
      {usersId: "6", gameId: "242", content: "Game is stupid!", score: "2"},
      {usersId: "7", gameId: "205", content: "HATE this game", score: "5"},
      {usersId: "8", gameId: "152", content: "Please help me, I'm stuck in a test project", score: "1"},
      {usersId: "9", gameId: "113", content: "I am 12 and what is this", score: "10"},
      {usersId: "10", gameId: "205", content: "I have played this game for 50000 hours", score: "6"},
      {usersId: "11", gameId: "28", content: "This game is so indie", score: "7"},
      {usersId: "12", gameId: "232", content: "This game is okay", score: "9"},
      {usersId: "13", gameId: "274", content: "This game is deep and made me think about life", score: "3"},
      {usersId: "14", gameId: "20", content: "Too much MTX", score: "6"},
      {usersId: "15", gameId: "243", content: "Not enough MTX", score: "10"},
      {usersId: "16", gameId: "256", content: "I like game", score: "10"},
      {usersId: "17", gameId: "152", content: "I REALLY like game", score: "3"},
      {usersId: "18", gameId: "31", content: "Game is stupid!", score: "8"},
      {usersId: "19", gameId: "275", content: "HATE this game", score: "9"},
      {usersId: "20", gameId: "234", content: "Please help me, I'm stuck in a test project", score: "5"},
      {usersId: "21", gameId: "266", content: "I am 12 and what is this", score: "5"},
      {usersId: "22", gameId: "262", content: "I have played this game for 50000 hours", score: "5"},
      {usersId: "23", gameId: "234", content: "This game is so indie", score: "4"},
      {usersId: "24", gameId: "170", content: "This game is okay", score: "1"},
      {usersId: "25", gameId: "158", content: "This game is deep and made me think about life", score: "6"},
      {usersId: "26", gameId: "259", content: "Too much MTX", score: "3"},
      {usersId: "27", gameId: "267", content: "Not enough MTX", score: "10"},
      {usersId: "28", gameId: "85", content: "I like game", score: "10"},
      {usersId: "1", gameId: "89", content: "I like game", score: "8"},
      {usersId: "2", gameId: "7", content: "I REALLY like game", score: "3"},
      {usersId: "3", gameId: "4", content: "Game is stupid!", score: "6"},
      {usersId: "4", gameId: "183", content: "HATE this game", score: "6"},
      {usersId: "5", gameId: "228", content: "Please help me, I'm stuck in a test project", score: "4"},
      {usersId: "6", gameId: "19", content: "I am 12 and what is this", score: "2"},
      {usersId: "7", gameId: "87", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "8", gameId: "245", content: "This game is so indie", score: "10"},
      {usersId: "9", gameId: "247", content: "This game is okay", score: "7"},
      {usersId: "10", gameId: "101", content: "This game is deep and made me think about life", score: "8"},
      {usersId: "11", gameId: "41", content: "Too much MTX", score: "5"},
      {usersId: "12", gameId: "66", content: "Not enough MTX", score: "3"},
      {usersId: "13", gameId: "260", content: "I like game", score: "9"},
      {usersId: "14", gameId: "66", content: "I REALLY like game", score: "6"},
      {usersId: "15", gameId: "101", content: "Game is stupid!", score: "5"},
      {usersId: "16", gameId: "121", content: "HATE this game", score: "5"},
      {usersId: "17", gameId: "261", content: "Please help me, I'm stuck in a test project", score: "10"},
      {usersId: "18", gameId: "84", content: "I am 12 and what is this", score: "8"},
      {usersId: "19", gameId: "191", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "20", gameId: "69", content: "This game is so indie", score: "10"},
      {usersId: "21", gameId: "52", content: "This game is okay", score: "3"},
      {usersId: "22", gameId: "126", content: "This game is deep and made me think about life", score: "10"},
      {usersId: "23", gameId: "201", content: "Too much MTX", score: "10"},
      {usersId: "24", gameId: "198", content: "Not enough MTX", score: "1"},
      {usersId: "25", gameId: "189", content: "I like game", score: "2"},
      {usersId: "26", gameId: "267", content: "I REALLY like game", score: "2"},
      {usersId: "27", gameId: "172", content: "Game is stupid!", score: "3"},
      {usersId: "28", gameId: "234", content: "HATE this game", score: "7"},
      {usersId: "1", gameId: "173", content: "Please help me, I'm stuck in a test project", score: "3"},
      {usersId: "2", gameId: "78", content: "I am 12 and what is this", score: "7"},
      {usersId: "3", gameId: "169", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "4", gameId: "192", content: "This game is so indie", score: "2"},
      {usersId: "5", gameId: "128", content: "This game is okay", score: "4"},
      {usersId: "6", gameId: "237", content: "This game is deep and made me think about life", score: "5"},
      {usersId: "7", gameId: "18", content: "Too much MTX", score: "1"},
      {usersId: "8", gameId: "153", content: "Not enough MTX", score: "1"},
      {usersId: "9", gameId: "54", content: "I like game", score: "5"},
      {usersId: "10", gameId: "265", content: "I REALLY like game", score: "7"},
      {usersId: "11", gameId: "66", content: "Game is stupid!", score: "3"},
      {usersId: "12", gameId: "192", content: "HATE this game", score: "2"},
      {usersId: "13", gameId: "237", content: "Please help me, I'm stuck in a test project", score: "4"},
      {usersId: "14", gameId: "233", content: "I am 12 and what is this", score: "5"},
      {usersId: "15", gameId: "156", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "16", gameId: "11", content: "This game is so indie", score: "7"},
      {usersId: "17", gameId: "135", content: "This game is okay", score: "1"},
      {usersId: "18", gameId: "215", content: "This game is deep and made me think about life", score: "2"},
      {usersId: "19", gameId: "178", content: "Too much MTX", score: "9"},
      {usersId: "20", gameId: "249", content: "Not enough MTX", score: "1"},
      {usersId: "21", gameId: "254", content: "I like game", score: "6"},
      {usersId: "22", gameId: "9", content: "I REALLY like game", score: "8"},
      {usersId: "23", gameId: "260", content: "Game is stupid!", score: "5"},
      {usersId: "24", gameId: "83", content: "HATE this game", score: "6"},
      {usersId: "25", gameId: "194", content: "Please help me, I'm stuck in a test project", score: "9"},
      {usersId: "26", gameId: "61", content: "I am 12 and what is this", score: "7"},
      {usersId: "27", gameId: "51", content: "I have played this game for 50000 hours", score: "2"},
      {usersId: "28", gameId: "124", content: "This game is so indie", score: "2"},
      {usersId: "1", gameId: "190", content: "This game is okay", score: "7"},
      {usersId: "2", gameId: "250", content: "This game is deep and made me think about life", score: "2"},
      {usersId: "3", gameId: "174", content: "Too much MTX", score: "5"},
      {usersId: "4", gameId: "105", content: "Not enough MTX", score: "8"},
      {usersId: "5", gameId: "106", content: "I like game", score: "3"},
      {usersId: "6", gameId: "235", content: "I like game", score: "3"},
      {usersId: "7", gameId: "262", content: "I REALLY like game", score: "7"},
      {usersId: "8", gameId: "24", content: "Game is stupid!", score: "7"},
      {usersId: "9", gameId: "6", content: "HATE this game", score: "10"},
      {usersId: "10", gameId: "149", content: "Please help me, I'm stuck in a test project", score: "8"},
      {usersId: "11", gameId: "102", content: "I am 12 and what is this", score: "8"},
      {usersId: "12", gameId: "187", content: "I have played this game for 50000 hours", score: "10"},
      {usersId: "13", gameId: "85", content: "This game is so indie", score: "5"},
      {usersId: "14", gameId: "179", content: "This game is okay", score: "4"},
      {usersId: "15", gameId: "262", content: "This game is deep and made me think about life", score: "6"},
      {usersId: "16", gameId: "163", content: "Too much MTX", score: "3"},
      {usersId: "17", gameId: "266", content: "Not enough MTX", score: "2"},
      {usersId: "18", gameId: "222", content: "I like game", score: "3"},
      {usersId: "19", gameId: "205", content: "I REALLY like game", score: "7"},
      {usersId: "20", gameId: "155", content: "Game is stupid!", score: "6"},
      {usersId: "21", gameId: "164", content: "HATE this game", score: "4"},
      {usersId: "22", gameId: "241", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "23", gameId: "24", content: "I am 12 and what is this", score: "2"},
      {usersId: "24", gameId: "120", content: "I have played this game for 50000 hours", score: "10"},
      {usersId: "25", gameId: "137", content: "This game is so indie", score: "2"},
      {usersId: "26", gameId: "56", content: "This game is okay", score: "2"},
      {usersId: "27", gameId: "53", content: "This game is deep and made me think about life", score: "8"},
      {usersId: "28", gameId: "240", content: "Too much MTX", score: "7"},
      {usersId: "1", gameId: "25", content: "Not enough MTX", score: "7"},
      {usersId: "2", gameId: "196", content: "Not enough MTX", score: "9"},
      {usersId: "3", gameId: "63", content: "I like game", score: "5"},
      {usersId: "4", gameId: "239", content: "I REALLY like game", score: "3"},
      {usersId: "5", gameId: "77", content: "Game is stupid!", score: "7"},
      {usersId: "6", gameId: "165", content: "HATE this game", score: "7"},
      {usersId: "7", gameId: "64", content: "Please help me, I'm stuck in a test project", score: "10"},
      {usersId: "8", gameId: "88", content: "I am 12 and what is this", score: "1"},
      {usersId: "9", gameId: "192", content: "I have played this game for 50000 hours", score: "5"},
      {usersId: "10", gameId: "80", content: "This game is so indie", score: "3"},
      {usersId: "11", gameId: "99", content: "This game is okay", score: "3"},
      {usersId: "12", gameId: "37", content: "This game is deep and made me think about life", score: "4"},
      {usersId: "13", gameId: "8", content: "Too much MTX", score: "5"},
      {usersId: "14", gameId: "31", content: "Not enough MTX", score: "10"},
      {usersId: "15", gameId: "232", content: "I like game", score: "9"},
      {usersId: "16", gameId: "96", content: "I REALLY like game", score: "6"},
      {usersId: "17", gameId: "146", content: "Game is stupid!", score: "6"},
      {usersId: "18", gameId: "240", content: "HATE this game", score: "3"},
      {usersId: "19", gameId: "4", content: "Please help me, I'm stuck in a test project", score: "5"},
      {usersId: "20", gameId: "148", content: "I am 12 and what is this", score: "10"},
      {usersId: "21", gameId: "233", content: "I have played this game for 50000 hours", score: "3"},
      {usersId: "22", gameId: "230", content: "This game is so indie", score: "3"},
      {usersId: "23", gameId: "169", content: "This game is okay", score: "9"},
      {usersId: "24", gameId: "262", content: "This game is deep and made me think about life", score: "1"},
      {usersId: "25", gameId: "122", content: "Too much MTX", score: "7"},
      {usersId: "26", gameId: "214", content: "Not enough MTX", score: "10"},
      {usersId: "27", gameId: "215", content: "I like game", score: "9"},
      {usersId: "28", gameId: "95", content: "I REALLY like game", score: "7"},
      {usersId: "1", gameId: "4", content: "Game is stupid!", score: "2"},
      {usersId: "2", gameId: "199", content: "HATE this game", score: "5"},
      {usersId: "3", gameId: "215", content: "Please help me, I'm stuck in a test project", score: "6"},
      {usersId: "4", gameId: "95", content: "I am 12 and what is this", score: "3"},
      {usersId: "5", gameId: "129", content: "I have played this game for 50000 hours", score: "1"},
      {usersId: "6", gameId: "68", content: "This game is so indie", score: "9"},
      {usersId: "7", gameId: "267", content: "This game is okay", score: "1"},
      {usersId: "8", gameId: "210", content: "This game is deep and made me think about life", score: "6"},
      {usersId: "9", gameId: "243", content: "Too much MTX", score: "1"},
      {usersId: "10", gameId: "28", content: "Not enough MTX", score: "2"},
      {usersId: "11", gameId: "87", content: "I like game", score: "10"},
      {usersId: "12", gameId: "175", content: "I like game", score: "5"},
      {usersId: "13", gameId: "85", content: "I REALLY like game", score: "4"},
      {usersId: "14", gameId: "257", content: "Game is stupid!", score: "7"},
      {usersId: "15", gameId: "179", content: "HATE this game", score: "5"},
      {usersId: "16", gameId: "200", content: "Please help me, I'm stuck in a test project", score: "7"},
      {usersId: "17", gameId: "153", content: "I am 12 and what is this", score: "5"},
      {usersId: "18", gameId: "120", content: "I have played this game for 50000 hours", score: "7"},
      {usersId: "19", gameId: "35", content: "This game is so indie", score: "8"},
      {usersId: "20", gameId: "173", content: "This game is okay", score: "3"},
      {usersId: "21", gameId: "226", content: "This game is deep and made me think about life", score: "5"},
      {usersId: "22", gameId: "216", content: "Too much MTX", score: "1"},
      {usersId: "23", gameId: "100", content: "Not enough MTX", score: "5"},
      {usersId: "24", gameId: "210", content: "I like game", score: "1"},
      {usersId: "25", gameId: "67", content: "I REALLY like game", score: "5"},
      {usersId: "26", gameId: "260", content: "Game is stupid!", score: "10"},
      {usersId: "27", gameId: "97", content: "HATE this game", score: "2"},
      {usersId: "28", gameId: "201", content: "Please help me, I'm stuck in a test project", score: "9"},
      {usersId: "1", gameId: "219", content: "I am 12 and what is this", score: "6"},
      {usersId: "2", gameId: "171", content: "I have played this game for 50000 hours", score: "9"},
      {usersId: "3", gameId: "116", content: "This game is so indie", score: "7"},
      {usersId: "4", gameId: "5", content: "This game is okay", score: "2"},
      {usersId: "5", gameId: "269", content: "This game is deep and made me think about life", score: "10"},
      {usersId: "6", gameId: "240", content: "Too much MTX", score: "3"},
      {usersId: "7", gameId: "100", content: "Not enough MTX", score: "3"}], {});
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
  }
};
